version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

# Install our python package before building the docs
python:
  install:
    - method: pip
      path: .
      extra_requirements: 
        - docs
