trigger:
  branches:
    include:
    - master
    - documentationtest

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    addToPath: true
    architecture: 'x64'

- script: |
    python -m pip install --upgrade pip wheel
    pip install '.[all]'
    pip install sphinx sphinx_rtd_theme numpydoc recommonmark sphinx-markdown-tables
  displayName: 'Install package and docs dependencies'

- script: |
    sphinx-build -b html docs/source/ docs/build/
  displayName: 'Build the documenation'

- task: AzureCLI@2
  inputs:
    scriptType: bash
    azureSubscription: ynformed-internal
    scriptLocation: inlineScript
    inlineScript: |
      az storage blob upload-batch --destination '$web' --source docs/build/ --account-name stsamdocs --auth-mode key
  displayName: 'Publish documentation as artifact'