trigger:
  branches:
    include:
    - master
  paths:
    include:
    - setup.cfg

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    addToPath: true
    architecture: 'x64'

# Install python distributions like wheel, twine etc
- script: python -m pip install --upgrade pip wheel setuptools twine
  displayName: 'Install tools'

# Build the python distribution from source
- script: python setup.py sdist bdist_wheel
  displayName: 'Build package'

- task: TwineAuthenticate@1
  inputs:
    artifactFeed: 'SAM/SAM'

- script: twine upload -r SAM --config-file $(PYPIRC_PATH) dist/*.whl
  displayName: 'Upload package'