name: Unit test

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  build:
    name: unittest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[all]"
        pip install ".[test]"
    - name: Running unit tests
      run: |
        pytest --mpl --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
    - name: Code coverage 
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        flags: unittests # optional
        name: codecov-umbrella # optional
        verbose: true # optional (default = false)
    - name: checking docstring examples
      run: |
        pytest --doctest-modules ./sam/*
